version: '3.9'

services:
  client:
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    build:
      dockerfile: Dockerfile
      context: ./car-tracking-client
    container_name: client
    volumes:
      - /app/node_modules
      - ./client:/app

  server:
    build:
      context: ./car-tracking-api
      dockerfile: Dockerfile
    container_name: node_server
    ports:
      - 3000:3000
      - 8000:8000
    volumes:
      - /app/node_modules
      - ./server:/app
    env_file:
      - .env

  postgres:
    image: postgres
    ports:
      - '5432:5432'
    env_file:
      - .env
    volumes:
      - 'postgres:/var/lib/postgresql/data'
