version: "3.9"

services:
    client:
        stdin_open: true
        environment:
            - CHOKIDAR_USEPOLLING=true
        build:
            dockerfile: Dockerfile
            context: ./car-tracking-client
        ports:
            - "3000:3000"
        container_name: client
        volumes:
            - ./car-tracking-client:/app
            - /app/node_modules

    server:
        build:
            context: ./car-tracking-api
            dockerfile: Dockerfile
        depends_on:
            - postgres
        container_name: node_server
        ports:
            - 8000:8000
        volumes:
            - ./car-tracking-api:/app
            - /app/node_modules
        env_file:
            - ./car-tracking-api/config/.env

    postgres:
        image: postgres
        environment:
            - POSTGRES_USER=root
            - POSTGRES_PASSWORD=toor
            - POSTGRES_DB=root
        ports:
            - "5432:5432"
        env_file:
            - ./car-tracking-api/config/.env
        volumes:
            - postgres:/var/lib/postgresql/data

    # PostgreSQL pgAdmin panel accessible at http://localhost:16543/
    pgadmin-compose:
        image: dpage/pgadmin4
        environment:
            PGADMIN_DEFAULT_EMAIL: "placeholder@example.com"
            PGADMIN_DEFAULT_PASSWORD: "fakepassword123!"
        ports:
            - "16543:80"
        depends_on:
            - postgres

volumes:
    postgres:
